// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLYsQDPJLMoKkMdz4FSAqP9pEwWER8ZnM',
    appId: '1:394236296692:web:1708e896858c904ffacda1',
    messagingSenderId: '394236296692',
    projectId: 'saji-editor',
    authDomain: 'saji-editor.firebaseapp.com',
    storageBucket: 'saji-editor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3a0QuSFjItzSOyB_YzY-I-1L-b07Oryw',
    appId: '1:394236296692:android:62f8232960d46ef5facda1',
    messagingSenderId: '394236296692',
    projectId: 'saji-editor',
    storageBucket: 'saji-editor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtIQSn3RO9nF3OgB37smaM8RN2dpQM0uY',
    appId: '1:394236296692:ios:93a8eadbb79676cffacda1',
    messagingSenderId: '394236296692',
    projectId: 'saji-editor',
    storageBucket: 'saji-editor.appspot.com',
    iosClientId: '394236296692-elmvi560r4ea3sqaqslae9mjlqv1kd7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sajiClient',
  );
}
